config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  resources :questions do
    resources :answers, only: %i[new create show] do
      resources :tasks, only: %i[index new update]
    end
  end

  resources :history, only: %i[index destroy]

  resources :tasks, only: %i[destroy]

  devise_for :users
  resources :tasks, only: %i[destroy]
  root to: "pages#home"

end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :content, presence: true

  belongs_to :question
  has_many :tasks, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, presence: true
  
  belongs_to :user
  has_one :answer
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :answer

  after_create :strip_numbers

  def strip_numbers
    self.content = self.content.gsub(/^\d[\)-\. ]-?/, "").strip.capitalize
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, :name, presence: true

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def set_locale
    I18n.locale = :fr # Or whatever logic you use to choose.
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  def index
    @questions = current_user.questions
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "History", template: "history/index", layout: "pdf"
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @question = Question.new
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    @question = Question.new(user_id: current_user.id, content: params[:question][:content])
    if @question.save
      sleep 2
      @answer = Answer.create(question_id: @question.id, content: call_client)
      @answer.content.split("\n")&.map { |element| element.gsub("\n", "") }.reject(&:empty?).each do |task_content|
        Task.create(answer_id: @answer.id, content: task_content)
      end
      redirect_to question_answer_tasks_path(@question, @answer)
    else
      render :new
    end
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)
    @answer = Answer.create(question_id: @question.id, content: call_client)
    @answer.content.split("\n")&.map { |element| element.gsub("\n", "") }.reject(&:empty?).each do |task_content|
      Task.create(answer_id: @answer.id, content: task_content)
    end
    redirect_to question_answer_tasks_path(@question, @answer)
  end

  private

  # def call_client
  #   client = OpenAI::Client.new
  #   response = client.completions(
  #     parameters: {
  #       model: "text-davinci-003",
  #       prompt: "Renvoie moi uniquement sous forme de listes les 5 meilleures solutions simple d'automédication autre qu'avec des médicaments pour soigner ces symptômes : #{@question.content}.",
  #       max_tokens: 300,
  #       temperature: 0.5,
  #     }
  #   )
  #   response['choices']&.first&.dig('text')
  # end

  def call_client
    client = OpenAI::Client.new
    response = client.chat(
      parameters: {
        model: "gpt-3.5-turbo",
        temperature: 0.1,
        messages: [
          {
            role: "user",
            content: "Renvoie moi uniquement sous forme de listes les 5 meilleures solutions simple d'automédication autre qu'avec des médicaments pour soigner ces symptômes : #{@question.content}.!"
          }
        ]
      })
    response.dig("choices", 0, "message", "content")
  end

  def question_params
    params.require(:question).permit(:content)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_answer, only: %i[create new index]
  before_action :set_question, only: %i[create new index]
  before_action :set_task, only: %i[update destroy]

  def index
    @tasks = Task.all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Tasks", template: "tasks/index", layout: "pdf"   # Excluding ".pdf" extension.
      end
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update(status: !@task.status)
    head :no_content
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to question_answer_tasks_path(@task.answer.question_id, @task.answer_id)
  end

  private

  def set_answer
    @answer = Answer.find(params[:answer_id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/history/index.html.erb
<div class="container home-bg d-flex justify-content-center p-4">
  <div class="shadow shadow-container bg-opacity-75 rounded-4">
    <div class="tab-pane">
      <h1 class="text-center p-4">Mon historique</h1>
      <ul class="list-inline p-4">
        <% @questions.order(created_at: :desc).each do |question| %>
          <div class="border border-start-0 border-end-0 border-5 d-flex justify-content-between p-2">
            <h3>Symptome: <%= question.content %></h3>
            <% if question&.answer %>
              <div class="d-flex justify-content-around">
                <div class="align-items-end"><%= image_tag 'pdf.png', class:"icon-pdf" %></div>
                    <div class="m-auto"><%= link_to "PDF", question_answer_tasks_path(question, question.answer, format: :pdf), target: :_blank, class: "text-decoration-none" %></div>
                  <div class="d-flex justify-content-between p-2 m-auto">
                    <div class="m-auto"><%= question.created_at.strftime('%d-%b-%Y - %Hh%M') %></div>
                  </div>
              </div>
            <% end %>
          </div>
          <div class="p-2">
            <% question.answer&.tasks&.each do |task|  %>
              <p><%= task.content %></p>
            <% end %>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/history/index.pdf.erb
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>

<div class="pdf-header">
    <h1>Pour retrouver <span>la forme</span></h1>
    <div class="symptom-container">
    <h3 class="symptom-title">Tes symptômes était:</h3>
    <%= @questions.each do |question| %>
    <%= question %>
    <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload", defer: true %>

    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <script src="https://unpkg.com/scrollreveal@4"></script>
    <script type="text/javascript" src="https://enhanceai.dev/library/enhanceai-v0.1.0.min.js"></script>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <script>
      ScrollReveal().reveal('.headline', { duration: 2000 });
      ScrollReveal().reveal('.widget', { interval: 200 });
    </script>
  </body>
</html>

app/views/layouts/pdf.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <%= wicked_pdf_image_tag 'mysite.jpg' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_modal.html.erb
<%# Bouton About %>

<button type="button" class="btn btn-about btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Medi, c'est quoi ?
</button>

<%# Modal %>


<div class="modal fade " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Medi, c'est quoi ?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Bienvenue dans l'ère de l'automédication 2.0 ! Avec notre application basée sur l'Intelligence Artificielle, vous pouvez maintenant soigner vos petits bobos sans quitter le confort de votre canapé.
<br>
<br>
Finies les heures passées à chercher sur Google vos symptômes, à essayer de deviner quelle pilule prendre ou à vous inquiéter inutilement. Notre application est là pour vous aider à gérer vos maux et douleurs en quelques clics.
<br>
<br>
Comment ça marche ? Tout d'abord, notre IA utilise des algorithmes sophistiqués pour analyser vos symptômes et établir un diagnostic rapide. Vous pouvez ensuite choisir parmi une sélection de traitements recommandés pour votre condition.
<br>
<br>
Alors pourquoi vous encombrer d'une visite chez le médecin lorsque vous pouvez avoir votre propre infirmier personnel dans votre poche ?
        <p>Et si vos symptômes persistent, n'hésitez pas à consulter un vrai médecin. On est quand même pas magiciens...</p>
      <div class="modal-footer">
      💙
      </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%# Section %>

<div class="container home-bg d-flex justify-content-center p-4">
  <div class="row home-input p-2 shadow rounded-4">
    <div class="col-12">
      <h1>Bienvenue chez <span class="badge text-bg-primary">Medi 💙</span></h1>
      <h4><span data-controller="typed-js"></span></h4>
      <div class="pt-4"><%= render "questions/input", question: @question %></div>
    </div>
  </div>
</div>

<%= render "pages/modal" %>

app/views/questions/_input.html.erb
<div class="row " data-controller="loading">
  <h4 class="input-question"> Peux-tu me dire tes <span class="flag">symptômes ?</span></h4>
  <%= simple_form_for question, data: {action: "submit->loading#loading"} do |f| %>
    <div class="col-auto pt-2">
      <%= f.input :content, label: false, input_html: { class: 'input-space enhanceai' }, data: { aicontext: "Quels sont tes symptômes ?"}, placeholder: "J'ai mal au ventre, courbatures, ..." %>
    </div>
    <div class="col-auto pt-4">
      <%= f.submit "Rechercher", class: "send-button" %>
    </div>
    <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container input-question d-flex align-items-center justify-content-center vh-100">
  <div class="shadow shadow-container p-4" data-controller="loading">
  <h1 class="fw-bold">As-tu d’autres symptomes ?</h1>
  <%= simple_form_for @question, data: {action: "submit->loading#loading"} do |f| %>
    <div class="col-auto pt-2">
      <%= f.input :content, label: false, input_html: { class: 'input-space enhanceai' }, placeholder: "J'ai mal au ventre, courbatures, ..." %>
    </div>
    <div class="col-auto pt-4">
      <%= f.submit "Rechercher", class: "send-button" %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container d-flex justify-content-center" style="margin-top: 100px;">
  <div class="input-question">
    <h1 class="fw-bold ">Peux-tu me dire tes symptômes ?</h1>
      <br>
      <%= render "input", question: @question %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top p-2">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar" do %>
    <%= image_tag "Sans titre (47).png", class: "avatar" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "menu1.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <%# <%= image_tag "menu2.png", class: "overlay", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <div class="dropdown-menu dropdown-menu-end shadow rounded-4" aria-labelledby="navbarDropdown">
              <%= link_to "Démarrer un bilan", new_question_path, class: "dropdown-item" %>
              <%= link_to "Historique", history_index_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class:'send-button text-decoration-none' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container home-bg d-flex align-items-center justify-content-center" data-controller="task">
  <div class="shadow shadow-container">
    <div class="p-4">
      <div class="d-flex justify-content-between">
        <h4 class="fw-bolder">Bonjour <span class="flag"><%= current_user.name %></span> 👋🏻</h4>
        <p> <%= image_tag 'pdf.png', class:"icon-pdf" %> <%= link_to "Télécharger ma fiche", question_answer_tasks_path(@question, @answer, format: :pdf), target: :_blank, class: "text-decoration-none" %></p>
      </div>
      <div class="d-flex gap-3"><p class="">J'ai bien pris en compte tes symptômes : </p> <div class="fw-bolder"> "<%= @question.content.capitalize %>"</div></div>
      <button class="border border-0 mt-3"><%= link_to "Modifier", edit_question_path(@question), class: "flag-m text-decoration-none" %></button></p>
    </div>
    <hr class="border border-5">
    <div class="p-4">
    <ul class="list-inline grid gap-0 column-gap-4">
      <li class="list-inline-item">
        <h3 class="fw-bolder"><%= "Les #{@answer.tasks.length} conseils de Medi" %></h3>
      </li>
      <li class="list-inline-item">
      </li>
      <li class="list-inline-item">
      </li>
      <div class="">
        <div class="col-2">
          <h5 class="">💙 Progression</h5>
        </div>
        <div class="progress rounded-4" role="progressbar" aria-label="Animated striped example" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
          <div class="progress-bar progress-bar-striped progress-bar-animated rounded-4" data-task-target="result" style="width: 100%"></div>
        </div>
      </div>
    </ul>
    </div>
    <div class="card-wrapper">
      <div class="slide-content">
        <div class="widget-list row" data-task-target="card">
          <% @answer.tasks.each do |task|%>
            <div class="shadow card mb-3 widget">
              <div class="card-header bg-transparent " >
                <div class="form-check">
                  <input data-action="click->task#update" class="form-check-input" type="checkbox" role="switch"  data-url="<%= question_answer_task_path(@question, @answer, task) %>" <%= "checked" if task.status  %> >
                  <%= button_to'╳', task_path(task), method: :delete, data: {turbo_method: :delete}, class:"button" %>
                </div>
              </div>
              <div class="card-body">
                <p class="description p-2" style="color: #000000;"><%= task.content %></p>
              <div class="card-footer bg-transparent">
                💙 +<span class="" data-task-target="score"></span>
                <span>%</span>
              </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <script>
      ScrollReveal().reveal('.headline', { duration: 2000 });
      ScrollReveal().reveal('.widget', { interval: 200 });
    </script>
  </div>
</div>

app/views/tasks/index.pdf.erb
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>

<div class="pdf-header">
    <h1>Pour retrouver <span>la forme</span></h1>
    <div class="symptom-container">
    <h3 class="symptom-title">Tes symptômes :</h3>
    <p class="symptom-tag"><%= @question.content.capitalize %>.</p>
    </div>
    <p class='conseil-text'>Les conseils de Medi :</p>
  </div>
<div>
      <%@answer.tasks.each do |task|%>
      <div class="task-container">
          <div class='empty-square-container'>
            <div class='empty-square'></div>
          </div>
          <p class="task-content"><%= task.content %></p>
      </div>
    <% end %>
  </div>
  <div>
  <p class="alert-message">Medi ne remplace pas un médecin. Si vos symptômes persistent, il est nécessaire de consulter un professionnel de la santé.</p>
  </div>
</div>